/// Flutter icons PollarIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PollarIcons
///      fonts:
///       - asset: fonts/PollarIcons.ttf
///
/// 
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class PollarIcons {
  PollarIcons._();

  static const _kFontFam = 'PollarIcons';
  static const String? _kFontPkg = null;

  static const IconData trust_medium_pressed = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust_medium_resting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust_small_pressed = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust_small_resting = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow_large = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow_medium = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_arrow_small = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData url = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_large_pressed = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_large_resting = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_small_pressed = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_small_resting = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_on = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_large = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_medium = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_small = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree_large_pressed = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree_large_resting = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree_medium_pressed = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree_medium_resting = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree_small_pressed = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_back_arrow = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anonymous = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anonymous_mask_pressed = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anonymous_mask_resting = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_medium = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_small = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_pressed = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_resting = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_mute_pressed = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_mute_resting = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_pressed = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_resting = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_agree_small = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_disagree_small = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_icon = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_large_pressed = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_large_resting = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_medium_pressed = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_medium_resting = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_small_pressed = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree_small_resting = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow_large = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow_medium = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow_small = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_profile_large = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_text_field_large = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_text_field_small = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData follow_pressed = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData follow_resting = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_medium = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_small = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif_pressed = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif_resting = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_pressed = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_resting = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_agree_swipe = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_disagree_swipe = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_next_picture_tap = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_previous_picture_tap = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_replies_swipe = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instructions_skip_swipe = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_down_pressed = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_down_resting = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lid = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_large_pressed = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_large_resting = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_medium_pressed = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_medium_resting = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_small_pressed = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_small_resting = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_options_large = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_options_small = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_picture_large = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_picture_small = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multimedia_pressed = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multimedia_resting = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_2_pressed = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_2_resting = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_large_pressed = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_large_resting = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_small_pressed = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute_small_resting = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_pressed = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_resting = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_large = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_chat_video = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_large = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_small = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polls_pressed = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polls_resting = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_pressed = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_resting = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_large = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_small = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_large = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_medium = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_small = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_large = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_medium = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_large = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_medium = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_pressed = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_resting = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_medium = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_large_pressed = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_large_resting = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_medium_pressed = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_medium_resting = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_small_pressed = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_small_resting = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_swipe_icon = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_backwards_large = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_backwards_small = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_forward_large = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_forward_small = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribe_pressed = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribe_resting = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust_large_pressed = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust_large_resting = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const List<IconData> _values = [
      PollarIcons.add_large,
      PollarIcons.add_medium,
      PollarIcons.add_small,
      PollarIcons.agree_large_pressed,
      PollarIcons.agree_large_resting,
      PollarIcons.agree_medium_pressed,
      PollarIcons.agree_medium_resting,
      PollarIcons.agree_small_pressed,
      PollarIcons.android_back_arrow,
      PollarIcons.anonymous_mask_pressed,
      PollarIcons.anonymous_mask_resting,
      PollarIcons.anonymous,
      PollarIcons.back_medium,
      PollarIcons.back_small,
      PollarIcons.block,
      PollarIcons.chat_mute_pressed,
      PollarIcons.chat_mute_resting,
      PollarIcons.chat_pressed,
      PollarIcons.chat_resting,
      PollarIcons.circle_agree_small,
      PollarIcons.circle_disagree_small,
      PollarIcons.delete_icon,
      PollarIcons.disagree_large_pressed,
      PollarIcons.disagree_large_resting,
      PollarIcons.disagree_medium_pressed,
      PollarIcons.disagree_medium_resting,
      PollarIcons.disagree_small_pressed,
      PollarIcons.disagree_small_resting,
      PollarIcons.down_arrow_large,
      PollarIcons.down_arrow_medium,
      PollarIcons.down_arrow_small,
      PollarIcons.edit_profile_large,
      PollarIcons.expand_text_field_large,
      PollarIcons.expand_text_field_small,
      PollarIcons.export_icon,
      PollarIcons.flag,
      PollarIcons.forward_medium,
      PollarIcons.forward_small,
      PollarIcons.gif_pressed,
      PollarIcons.gif_resting,
      PollarIcons.home_pressed,
      PollarIcons.home_resting,
      PollarIcons.information,
      PollarIcons.instructions_agree_swipe,
      PollarIcons.instructions_disagree_swipe,
      PollarIcons.instructions_next_picture_tap,
      PollarIcons.instructions_previous_picture_tap,
      PollarIcons.instructions_replies_swipe,
      PollarIcons.instructions_skip_swipe,
      PollarIcons.keyboard_down_pressed,
      PollarIcons.keyboard_down_resting,
      PollarIcons.like_large_pressed,
      PollarIcons.like_large_resting,
      PollarIcons.like_medium_pressed,
      PollarIcons.like_medium_resting,
      PollarIcons.like_small_pressed,
      PollarIcons.like_small_resting,
      PollarIcons.location,
      PollarIcons.more_options_large,
      PollarIcons.more_options_small,
      PollarIcons.multi_picture_large,
      PollarIcons.multi_picture_small,
      PollarIcons.multimedia_pressed,
      PollarIcons.multimedia_resting,
      PollarIcons.mute_large_pressed,
      PollarIcons.mute_large_resting,
      PollarIcons.new_pressed,
      PollarIcons.mute_small_resting,
      PollarIcons.new_resting,
      PollarIcons.play_small,
      PollarIcons.polls_resting,
      PollarIcons.play_large,
      PollarIcons.profile_pressed,
      PollarIcons.profile_resting,
      PollarIcons.remove_large,
      PollarIcons.remove_small,
      PollarIcons.return_medium,
      PollarIcons.search_medium,
      PollarIcons.refresh_large,
      PollarIcons.refresh_small,
      PollarIcons.remove_medium,
      PollarIcons.return_large,
      PollarIcons.pause_large,
      PollarIcons.send_pressed,
      PollarIcons.play_chat_video,
      PollarIcons.share_medium_pressed,
      PollarIcons.search_large,
      PollarIcons.mute_small_pressed,
      PollarIcons.send_resting,
      PollarIcons.share_large_pressed,
      PollarIcons.settings_medium,
      PollarIcons.share_large_resting,
      PollarIcons.share_medium_resting,
      PollarIcons.polls_pressed,
      PollarIcons.share_small_pressed,
      PollarIcons.share_small_resting,
      PollarIcons.share,
      PollarIcons.skip_backwards_large,
      PollarIcons.skip_backwards_small,
      PollarIcons.skip_forward_large,
      PollarIcons.skip_forward_small,
      PollarIcons.trust_large_pressed,
      PollarIcons.trust_large_resting,
      PollarIcons.trust_medium_pressed,
      PollarIcons.trust_medium_resting,
      PollarIcons.trust_small_pressed,
      PollarIcons.trust_small_resting,
      PollarIcons.up_arrow_large,
      PollarIcons.up_arrow_medium,
      PollarIcons.up_arrow_small,
      PollarIcons.url,
      PollarIcons.visible_large_resting,
      PollarIcons.visible_large_pressed,
      PollarIcons.visible_small_pressed,
      PollarIcons.visible_small_resting,
      PollarIcons.volume_on,
      PollarIcons.volume_off
    ];

  static List<IconData> get values => PollarIcons._values;

  static IconData index(int index){
    
    if(index == null || index >= _values.length || index < 0){
      return Icons.square_foot_rounded;
    }

    return _values[index];

  }
}